### ISSUE TITLE
How to evaluate on Imagenet？

### ISSUE THREAD

**Issue by zuwenqiang** [rezaakb/peft-vit#1]
Hello, I successfully run the fine-tuning. And how can i run evaluation?

**Comment by rezaakb** [comment]
Hello,

You can run the evaluation using the following command:

`python src/eval_knn_cifar.py
 --training_mode=MODE 
 --weights=PATH_TO_WEIGHTS`
 
 `MODE` can be `full`, `lora`, or `block`. I hope this works for you.
