### ISSUE TITLE
Potential issue in the KNN calculation

### ISSUE THREAD

**Issue by hedjazi** [rezaakb/peft-vit#2]
Thank you for your fascinating work.

I encountered several issues related to DDP while using the knn_eval.py script, but the major problem lies in line 261:

https://github.com/rezaakb/peft-vit/blob/5095e75ef45018baef7ccf935ba6095b6d030d9b/src/eval_knn.py#L261

The data loader is returning the image and the index (not the label), but the KNN calculation requires the label. Could you please clarify this? I have been unable to reproduce the ImageNet1k accuracy using the trained model on CIFAR-100 with block expansion.

I was able to reproduce the results on CIFAR-100:

![image](https://github.com/rezaakb/peft-vit/assets/32842839/8a6580c8-e868-45f6-be39-0828686f8dee)

But the results on ImagetNet1k:

![image](https://github.com/rezaakb/peft-vit/assets/32842839/5c665f3e-bcf8-401f-bcb3-db13f66e5a9f)

Thank you.

**Comment by rezaakb** [comment]
Thank you so much for using our code and reporting this issue. Yes, we need to modify the k-NN code and write documentation for it.

Regarding your issue, I believe the indexes should be fine. We used the k-NN evaluation from [here](https://github.com/facebookresearch/dino/blob/main/eval_knn.py). Can you check if the model initialized correctly with expanded blocks? You need to pass the arguments that you used for expansion (e.g., split) to this code.

**Comment by hedjazi** [comment]
Thank you for your response. I also couldn't reproduce the results using just the pretrained model. I believe there are numerous issues in the knn_eval script.

**Comment by hedjazi** [comment]
Yes, I think there may have some problems loading the checkpoint, I will check it. Thank you.
